export const siteConfig = {
  name: 'Vivek Jindal',
  title: 'Associate Software Engineer at Accenture | AI/ML Researcher',
  description:
    'Associate Software Engineer at Accenture. M.Tech (2025) in Computer Science & Engineering from Medicaps University. Specialized in deep learning, computer vision, and neural networks with 7 research publications and 2 patents.',
  url: 'https://www.vivekjindal.in',
  ogImage: '/og-image.jpg',
  links: {
    email: 'vivek.jindal24@outlook.com',
    github: 'https://github.com/vivekjindal',
    linkedin: 'https://www.linkedin.com/in/24vivek-jindal',
    whatsapp: '+919755872328',
  },
  keywords: [
    'Vivek Jindal',
    'Deep Learning',
    'Computer Vision',
    'Machine Learning',
    'CNN',
    'Neural Networks',
    'M.Tech',
    'Medicaps University',
    'Research',
    'Cricket Scorecard Automation',
    'Plant Disease Detection',
    'Oracle APEX',
    'Oracle APEX Cloud Developer',
    'Oracle Certification',
  ],
};
